travis:
  secure:
    BINSTAR_TOKEN: TTYof0sxdhUOeNF709N6ahvycx+Qo4aLVUhAp3ypy6Ylo48/6D1tZGlSF+JlvoFGvyCrWWjmP5E4NoRWNmgjIFoyIAR0d+Zobk91EyugMxDmoQGG8o+EJcmxWhVvoOzXnPccBK2nikXWWLb+x9CKy9XLPLfRpyuK0oid6GNQf6E+bYeTjl6Bqo60nH1qvuGKiymfGspMRJmKbBMpV6nblRlnDWjiof1zKn/Zz2v9aii6W6FnTE1bgAwcjrGemgudE0gb07I5odgmx1cEI5TaPKPAGviRoRnC8upZpmcfYHeQvzcrlInvCqzBMy1DgEyIo6GWX7f1JGm9h7GvSsVDb7ZromdWXk/+V64ertROS0ESgv62gc8mKlks5OWXT5qYjOHdCJoWp71FOGE0iRqq7dhk4U3uiYyFzA3jYJyhQOLT0WJKkLpq7bP2KhI21Vh7OIcqXlraQyweXv/05uJ+P2r1AqutKkfSxVSDc6j7Lc7zHGGmHYSAlIDQUZDX4tjeyRaJfvRpYle3rvlWG8S7Neqf2bq+uVBIpT5sPAGoxuDttgaiyQQHobyppARXyvOxJsOWls6I/5Z/m4dwWTV+2hRKhMCn+DP/y2vJHuq/7BmzPoGT5Hv+AFaZLCjKLOMsSmRu5DPQB81+O26UQxzz2cya41V7pZReIQ9ZP74uN8o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
